replicaCount: 1

image:
  repository: registry.totalsoft.local/librechat-dev-custom
  tag: latest
  pullPolicy: Always

hostAliases:
  - ip: "10.1.48.101"
    hostnames:
      - "keycloak.totalsoft.local"
  - ip: "10.1.48.101"
    hostnames:
      - "mcp.totalsoft.local"
  - ip: "10.1.48.101"
    hostnames:
      - "erp-reports.totalsoft.local"
# This will be populated from the command line, but you can also set it manually here
imagePullSecrets: []
# - name: regcred

persistence:
  enabled: false

volumes:
  - name: librechat-config
    configMap:
      name: librechat-config

volumeMounts:
  - name: librechat-config
    mountPath: /app/librechat.yaml
    subPath: librechat.yaml

config:
  envSecrets:
    secretRef: librechat-secrets

  env:
    NODE_ENV: "production"
    ALLOW_PASSWORD_RESET: "true"
    SEARCH: "true"
    ALLOW_EMAIL_LOGIN: "false"
    ALLOW_REGISTRATION: "false"
    ALLOW_SOCIAL_LOGIN: "true"
    ALLOW_SOCIAL_REGISTRATION: "false"
    APP_TITLE: "Tessa"
    CUSTOM_FOOTER: ""
    DEBUG_CONSOLE: "true"
    DEBUG_LOGGING: "true"
    DEBUG_OPENAI: "true"
    NODE_TLS_REJECT_UNAUTHORIZED: "0"
    OPENID_CALLBACK_URL: "/oauth/openid/callback"
    OPENID_SCOPE: "openid profile email"
    OPENID_AUTO_REDIRECT: "false"
    DEBUG_OPENID_REQUESTS: "true"
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: false #error if set to true with the api version, needs to be fixed in the main branch
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true 
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: librechat-dev.totalsoft.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: totalsoft-wildcard-tls
      hosts:
        - librechat-dev.totalsoft.local

mongodb:
  enabled: false

vectordb:
  enabled: false

meilisearch:
  enabled: false

rag_api:
  enabled: false

nodeSelector:
  kubernetes.io/os: linux
